apiVersion: v1
kind: Service
metadata:
  name: app-pagamentos
  labels:
    app: app-pagamentos
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: port-default
    - port: 8080
      targetPort: 8081
      name: port-fallback
  selector:
    app: app-pagamentos
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pagamentos
  labels:
    app: app-pagamentos
spec:
  selector:
    matchLabels:
      app: app-pagamentos
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-pagamentos
        tier: frontend
    spec:
      containers:
        - name: app-pagamentos
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              value: pagamento_58
            - name: MYSQL_HOST
              value: DB_HOST
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: PEDIDOS_SERVICE
              value: app-pedido
            - name: QR_URL
              value: QR_URL_VALUE
            - name: MP_TOKEN
              value: MP_TOKEN_VALUE
            - name: PAGAMENTO_WH
              value: PAGAMENTO_WH_VALUE
            - name: PEDIDOS_QUEUE
              value: pedidos-queue
            - name: PAGAMENTOS_CRIADOS_QUEUE
              value: pagamentos-criados-queue
            - name: PAGAMENTOS_CONFIRMADOS_QUEUE
              value: pagamentos-confirmados-queue
            - name: PAGAMENTOS_CANCELADOS_QUEUE
              value: pagamentos-cancelados-queue

          ports:
            - containerPort: 8081
              name: app-pagamento
          command: ["/bin/bash", "-c"]
          args:
            - |
              mvn clean package
              mvn spring-boot:run
          resources:
            requests:
              cpu: 700m