INSERT INTO Pagamentos (ID_PEDIDO, QR_CODE, IN_STORE_ORDER_ID, VALOR_TOTAL, STATUS, CRIADO_EM, ATUALIZADO_EM)
VALUES (4, 'XXXXX', 'yyyy', 10.20, 'CRIADO', NOW(), NOW()),
       (6, 'XXXXY', 'zzzzz', 11.20, 'PAGO', NOW(), NOW());