CREATE TABLE Pagamentos (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT,
    QR_CODE VARCHAR(250),
    IN_STORE_ORDER_ID VARCHAR(250),
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP
);