name: Deploy Actions
on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes unit치rios
        run: |
          export QR_URL="${{ secrets.QR_URL }}"
          export MP_TOKEN="${{ secrets.MP_TOKEN }}"
          export PAGAMENTO_WH="${{ secrets.PAGAMENTO_WH }}"
          export PEDIDOS_SERVICE="${{ secrets.PEDIDOS_SERVICE }}"
          mvn clean
          mvn test -P test

      - name: Generate JaCoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1

      - name: Log coverage percentage
        run:
          echo "coverage = ${{ steps.jacoco.ouputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          package: '*.jar'

      - name: Build com Maven
        run: |
          export QR_URL="${{ secrets.QR_URL }}"
          export MP_TOKEN="${{ secrets.MP_TOKEN }}"
          export PAGAMENTO_WH="${{ secrets.PAGAMENTO_WH }}"
          export PEDIDOS_SERVICE="${{ secrets.PEDIDOS_SERVICE }}"
          mvn package -P test


  publish:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3
      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          package: '*.jar'
      - name: Publish package
        run: |
          export QR_URL="${{ secrets.QR_URL }}"
          export MP_TOKEN="${{ secrets.MP_TOKEN }}"
          export PAGAMENTO_WH="${{ secrets.PAGAMENTO_WH }}"
          export PEDIDOS_SERVICE="${{ secrets.PEDIDOS_SERVICE }}"
          mvn --batch-mode deploy -P test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
